### ISSUE TITLE
Update Options

### ISSUE THREAD

**Issue by moinakbarali** [LarryBattle/jquery.filterOptions#1]
Hi

I have script that when I filter records through your plugin then I remove the selected options, but when I undo the filter that option(s) is still there, is there any way I can remove from cached options specific options?

Thanks.

**Comment by LarryBattleWork** [comment]
When you update your selections to a new set of options, try removing the data options from the element.

    $("#selection").removeData("options")

If that doesn't work, then try setting the options yourself.
Example:

	var $selection = $("#selection")
	var newBaseOptions = $selection.data("options").filter(function () {
		???
	});
	$selection.data("options", newBaseOptions)

Hope that helps.

**Comment by LarryBattle** [comment]
When you update your selections to a new set of options, try removing the data options from the element.

```
$("#selection").removeData("options")
```

If that doesn't work, then try setting the options yourself.
Example:

```
var $selection = $("#selection")
var newBaseOptions = $selection.data("options").filter(function () {
    ???
});
$selection.data("options", newBaseOptions)
```

Hope that helps.

**Comment by moinakbarali** [comment]
Okay, Thank you. Somehow I make it worked using your code.
